apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: L2Advertisement
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"L2Advertisement","metadata":{"annotations":{},"name":"12-pool","namespace":"metallb-system"},"spec":{"ipAddressPools":["first-pool"]}}
    creationTimestamp: "2025-03-22T16:04:31Z"
    generation: 1
    name: 12-pool
    namespace: metallb-system
    resourceVersion: "5971"
    uid: 7eda9dc6-d9bc-43de-854e-9c33db9751f3
  spec:
    ipAddressPools:
    - first-pool
kind: List
metadata:
  resourceVersion: ""
