apiVersion: v1
items:
- apiVersion: autoscaling.k8s.io/v1
  kind: VerticalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"autoscaling.k8s.io/v1","kind":"VerticalPodAutoscaler","metadata":{"annotations":{},"name":"open5gs-upf-vpa","namespace":"default"},"spec":{"resourcePolicy":{"containerPolicies":[{"containerName":"*","controlledResources":["cpu","memory"],"controlledValues":"RequestsOnly","maxAllowed":{"cpu":"1500m","memory":"512Mi"},"minAllowed":{"cpu":"25m","memory":"128Mi"}}]},"targetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"open5gs-upf"},"updatePolicy":{"updateMode":"InPlaceOrRecreate"}}}
    creationTimestamp: "2026-01-18T23:58:18Z"
    generation: 9
    name: open5gs-upf-vpa
    namespace: default
    resourceVersion: "14492742"
    uid: 79f995f0-8db8-4586-bd76-95b77c5ce6ed
  spec:
    resourcePolicy:
      containerPolicies:
      - containerName: '*'
        controlledResources:
        - cpu
        - memory
        controlledValues: RequestsOnly
        maxAllowed:
          cpu: 1500m
          memory: 512Mi
        minAllowed:
          cpu: 25m
          memory: 128Mi
    targetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: open5gs-upf
    updatePolicy:
      updateMode: InPlaceOrRecreate
  status:
    conditions:
    - lastTransitionTime: "2026-01-19T23:55:43Z"
      status: "True"
      type: RecommendationProvided
    recommendation:
      containerRecommendations:
      - containerName: open5gs-upf
        lowerBound:
          cpu: 25m
          memory: 250Mi
        target:
          cpu: 25m
          memory: 250Mi
        uncappedTarget:
          cpu: 25m
          memory: 250Mi
        upperBound:
          cpu: 25m
          memory: 250Mi
kind: List
metadata:
  resourceVersion: ""
