{
 "title": "UPF_monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase, namespace)"
    }
   },
   {
    "name": "upf_pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\", pod=~\".*upf.*\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "UPF CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{\r\n    namespace=\"$namespace\",\r\n    pod=~\"$upf_pod\",\r\n    container!=\"\",\r\n    image!=\"\",\r\n    container!=\"POD\"\r\n  }[$__rate_interval])\r\n)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "UPF memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_working_set_bytes{\r\n    namespace=\"$namespace\",\r\n    pod=~\"$upf_pod\",\r\n    container!=\"\",\r\n    image!=\"\",\r\n    container!=\"POD\"\r\n  }\r\n)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "VPA CPU target recommendation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "vpa_recommendation_cpu_cores{\r\n  exported_namespace=\"default\",\r\n  vpa=\"open5gs-upf-vpa\",\r\n  target_name=\"open5gs-upf\",\r\n  bound=~\"lower_bound\"\r\n}",
     "legendFormat": "Lower Bound"
    },
    {
     "expr": "vpa_recommendation_cpu_cores{\r\n  exported_namespace=\"default\",\r\n  vpa=\"open5gs-upf-vpa\",\r\n  target_name=\"open5gs-upf\",\r\n  bound=~\"target\"\r\n}",
     "legendFormat": "Target"
    },
    {
     "expr": "vpa_recommendation_cpu_cores{\r\n  exported_namespace=\"default\",\r\n  vpa=\"open5gs-upf-vpa\",\r\n  target_name=\"open5gs-upf\",\r\n  bound=~\"upper_bound\"\r\n}",
     "legendFormat": "Upper Bound"
    }
   ]
  },
  {
   "title": "VPA memory target recommendation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vpa_recommendation_memory_bytes{\r\n  exported_namespace=\"default\",\r\n  vpa=\"open5gs-upf-vpa\",\r\n  target_name=\"open5gs-upf\",\r\n  bound=~\"lower_bound\"\r\n}",
     "legendFormat": "Lower Bound"
    },
    {
     "expr": "vpa_recommendation_memory_bytes{\r\n  exported_namespace=\"default\",\r\n  vpa=\"open5gs-upf-vpa\",\r\n  target_name=\"open5gs-upf\",\r\n  bound=~\"target\"\r\n}",
     "legendFormat": "Target"
    },
    {
     "expr": "vpa_recommendation_memory_bytes{\r\n  exported_namespace=\"default\",\r\n  vpa=\"open5gs-upf-vpa\",\r\n  target_name=\"open5gs-upf\",\r\n  bound=~\"upper_bound\"\r\n}",
     "legendFormat": "Upper Bound"
    }
   ]
  },
  {
   "title": "UPF CPU usage vs request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{\r\n    namespace=\"$namespace\",\r\n    pod=~\"$upf_pod\",\r\n    container!=\"\",\r\n    image!=\"\",\r\n    container!=\"POD\"\r\n  }[$__rate_interval])\r\n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum by (pod) (\r\n  kube_pod_container_resource_requests{\r\n    namespace=\"$namespace\",\r\n    pod=~\"$upf_pod\",\r\n    resource=\"cpu\"\r\n  }\r\n)",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "UPF CPU usage vs request vs VPA target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{\r\n    namespace=\"$namespace\",\r\n    pod=~\"$upf_pod\",\r\n    container!=\"\",\r\n    image!=\"\",\r\n    container!=\"POD\"\r\n  }[$__rate_interval])\r\n)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum by (pod) (\r\n  kube_pod_container_resource_requests{\r\n    namespace=\"$namespace\",\r\n    pod=~\"$upf_pod\",\r\n    resource=\"cpu\"\r\n  }\r\n)",
     "legendFormat": "CPU request"
    },
    {
     "expr": "vpa_recommendation_cpu_cores{\r\n  exported_namespace=\"default\",\r\n  vpa=\"open5gs-upf-vpa\",\r\n  target_name=\"open5gs-upf\",\r\n  bound=\"target\"\r\n}",
     "legendFormat": "VPA Target"
    }
   ]
  },
  {
   "title": "UPF TX throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "8 * sum by (pod) (\r\n  rate(container_network_transmit_bytes_total{\r\n    namespace=\"$namespace\",\r\n    pod=~\"$upf_pod\"\r\n  }[$__rate_interval])\r\n)",
     "legendFormat": "TX Throughput"
    }
   ]
  },
  {
   "title": "UPF total throughput RX + TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * (\r\n  sum by (pod) (\r\n    rate(container_network_receive_bytes_total{\r\n      namespace=\"$namespace\",\r\n      pod=~\"$upf_pod\"\r\n    }[$__rate_interval])\r\n  )\r\n  +\r\n  sum by (pod) (\r\n    rate(container_network_transmit_bytes_total{\r\n      namespace=\"$namespace\",\r\n      pod=~\"$upf_pod\"\r\n    }[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "Total Throughput"
    }
   ]
  },
  {
   "title": "UPF RX throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * sum by (pod) (\r\n  rate(container_network_receive_bytes_total{\r\n    namespace=\"$namespace\",\r\n    pod=~\"$upf_pod\"\r\n  }[$__rate_interval])\r\n)",
     "legendFormat": "RX Throughput"
    }
   ]
  },
  {
   "title": "UPF memory usage vs request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_working_set_bytes{\r\n    namespace=\"$namespace\",\r\n    pod=~\"$upf_pod\",\r\n    container!=\"\",\r\n    image!=\"\",\r\n    container!=\"POD\"\r\n  }\r\n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum by (pod) (\r\n  kube_pod_container_resource_requests{\r\n    namespace=\"$namespace\",\r\n    pod=~\"$upf_pod\",\r\n    resource=\"memory\"\r\n  }\r\n)",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "UPF memory usage vs request vs VPA target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_working_set_bytes{\r\n    namespace=\"$namespace\",\r\n    pod=~\"$upf_pod\",\r\n    container!=\"\",\r\n    image!=\"\",\r\n    container!=\"POD\"\r\n  }\r\n)",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum by (pod) (\r\n  kube_pod_container_resource_requests{\r\n    namespace=\"$namespace\",\r\n    pod=~\"$upf_pod\",\r\n    resource=\"memory\"\r\n  }\r\n)",
     "legendFormat": "Memory Request"
    },
    {
     "expr": "vpa_recommendation_memory_bytes{\r\n  exported_namespace=\"default\",\r\n  vpa=\"open5gs-upf-vpa\",\r\n  target_name=\"open5gs-upf\",\r\n  bound=\"target\"\r\n}",
     "legendFormat": "VPA Target"
    }
   ]
  },
  {
   "title": "UPF pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  kube_pod_container_status_restarts_total{\r\n    namespace=\"$namespace\",\r\n    pod=~\"$upf_pod\"\r\n  }\r\n)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "UPF pod phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 40 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{\r\n  namespace=\"$namespace\",\r\n  pod=~\"$upf_pod\",\r\n  phase=~\"Running\"\r\n}",
     "legendFormat": "Running"
    },
    {
     "expr": "kube_pod_status_phase{\r\n  namespace=\"$namespace\",\r\n  pod=~\"$upf_pod\",\r\n  phase=~\"Pending\"\r\n}",
     "legendFormat": "Pending"
    },
    {
     "expr": "kube_pod_status_phase{\r\n  namespace=\"$namespace\",\r\n  pod=~\"$upf_pod\",\r\n  phase=~\"Failed\"\r\n}",
     "legendFormat": "Failed"
    }
   ]
  }
 ]
}