apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: ServiceCIDR
  metadata:
    creationTimestamp: "2026-01-12T23:53:46Z"
    finalizers:
    - networking.k8s.io/service-cidr-finalizer
    name: kubernetes
    resourceVersion: "2166636"
    uid: de065ead-324d-4a71-a5f1-721ef16fefb6
  spec:
    cidrs:
    - 10.43.0.0/16
  status:
    conditions:
    - lastTransitionTime: "2026-01-12T23:54:08Z"
      message: Kubernetes Service CIDR is ready
      reason: ""
      status: "True"
      type: Ready
kind: List
metadata:
  resourceVersion: ""
